ninetynine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats 






end

ninetynine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninetynine_cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    ActionView::Helpers::DateHelper
    COLORS = ["black", "white", "grey", "brown", "orange", "pink"]
    validates :color, inclusion: {in: COLORS, message: "%{value} is not a valid color"}
    validates :sex, inclusion: {in: %w(M F)}
    validates :name, presence: true 
    validates :description, presence: true 
    validates :birth_date, presence: true 
    

    def age
        present = 2021
        present - self.birth_date.year 
    end


end

ninetynine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninetynine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController 
    def index 
        @cats = Cat.all
        render :index 
    end

    def show 
        @kitty = Cat.find(params[:id])
        if @kitty
            render :show
        else
            redirect_to cats_url
        end
        
    end


    def new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            render :create
        else
            render json: @cat.errors.full_messages, status: :unprocessable_entity 
        end
    end



    private
    def cat_params
        cat_params = params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
    end

end

#  def method
#     var = 3
#     function
#  end

#  def function
#     var + 1
#  end

ninetynine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninetynine_cats/app/views/cats/index.html.erb
<h1> All our cats!</h1> 

   
    <ul>
    <% @cats.each do |cat| %>   
        <li><a href=<%=cat_url(cat)%>> <%= cat.name.capitalize %></a></li>
    <% end %>    

    </ul>


    

ninetynine_cats/app/views/cats/new.html.erb
<h1>Add Cat to our collection of lovely felines!</h1>


ninetynine_cats/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @kitty.name.capitalize %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Age:</td>
            <td><%= @kitty.age %></td>
        </tr>
        <tr>
            <td>Birth_Date:</td>
            <td><%= @kitty.birth_date %></td>
        </tr>
        <tr>
            <td>Color:</td>
            <td><%= @kitty.color.capitalize%></td>
        </tr>
        <tr>
            <td>Sex:</td>
            <td><%= @kitty.sex %></td>
        </tr>
    </tbody>
</table>

ninetynine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetynineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>